[package]
name = "av1an-scene-detection"
version = "0.1.0"
edition = "2018"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
av-scenechange = "0.5.0"
anyhow = "1.0.42"
y4m = "0.7.0"
