pull_request_rules:
  - name: automatic merge for main when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=master
    actions:
      queue:
        name: default
        method: squash
        rebase_fallback: none
        update_method: rebase
  - name: automatic merge for stable backports when CI passes
    conditions:
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=stable
      - or:
          - "#approved-reviews-by>=1"
          - author=mergify[bot]
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: none
        update_method: rebase
  - name: copy patches to stable branch
    conditions:
      - base=master
      - label!=unstable
    actions:
      backport:
        branches:
          - stable
  - name: assign code owners to stable merge conflicts
    conditions:
      - conflict
      - base=stable
    actions:
      assign:
        add_users:
          - master-of-zen
          - redzic
          - shssoichiro

queue_rules:
  - name: default
    conditions:
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
