pull_request_rules:
  - name: automatic merge for main when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      # Unfortunately, we cannot just say "all CI must pass".
      # This is not a bot limitation, but a limitation in Github itself.
      - check-success=tests / baseline aom
      - check-success=tests / baseline-select aom
      - check-success=tests / target-quality aom
      - check-success=tests / probe-slow aom
      - check-success=tests / baseline rav1e
      - check-success=tests / baseline-select rav1e
      - check-success=tests / target-quality rav1e
      - check-success=tests / probe-slow rav1e
      - check-success=tests / baseline svt-av1
      - check-success=tests / baseline-select svt-av1
      - check-success=tests / target-quality svt-av1
      - check-success=tests / probe-slow svt-av1
      - check-success=tests / baseline vpx
      - check-success=tests / baseline-select vpx
      - check-success=tests / target-quality vpx
      - check-success=tests / probe-slow vpx
      - check-success=tests / baseline x265
      - check-success=tests / baseline-select x265
      - check-success=tests / target-quality x265
      - check-success=tests / probe-slow x265
      - check-success=tests / baseline x264
      - check-success=tests / baseline-select x264
      - check-success=tests / target-quality x264
      - check-success=tests / probe-slow x264
      - check-success=tests / chunk_hybrid aom
      - check-success=tests / chunk_select aom
      - check-success=tests / chunk_ffms2 aom
      - check-success=tests / chunk_lsmash aom
      - check-success=tests / scenes aom
      - check-success=tests / workers aom
      - check-success=tests / vmaf aom
      - check-success=tests / extra_splits aom
      - check-success=tests / video_settings aom
      - check-success=tests / temp aom
      - check-success=tests / docker
      - check-success=SonarCloud Code Analysis
      - base=master
    actions:
      merge:
        method: squash
        rebase_fallback: none
        strict: smart+fasttrack
        strict_method: rebase
  - name: copy patches to stable branch
    conditions:
      - base=master
      - label!=unstable
    actions:
      backport:
        branches:
          - stable
        assignees:
          - "@master-of-zen"
          - "@redzic"
          - "@shssoichiro"
