pull_request_rules:
  - name: automatic squash-merge for master when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=master
    actions:
      queue:
        name: default
        method: squash
        rebase_fallback: none
        update_method: rebase
  - name: automatic merge for stable when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
      - base=stable
    actions:
      queue:
        name: default
        method: rebase
        rebase_fallback: merge
        update_method: rebase

queue_rules:
  - name: default
    conditions:
      - and:
          # Unfortunately, we cannot just say "all CI must pass".
          # This is not a bot limitation, but a limitation in Github itself.
          - check-success=all-tests
          - check-success=docker
          - check-success=SonarCloud Code Analysis
