pull_request_rules:
  - name: automatic merge for main when CI passes and approved
    conditions:
      - "#approved-reviews-by>=1"
      # Unfortunately, we cannot just say "all CI must pass".
      # This is not a bot limitation, but a limitation in Github itself.
      - or:
          - and:
              - check-success=tests / all-tests
              - check-success=tests / docker
          - and:
              - check-success=tests / all-tests (pull_request)
              - check-success=tests / docker (pull_request)
      - check-success=SonarCloud Code Analysis
      - base=master
    actions:
      queue:
        name: default
        method: squash
        rebase_fallback: none
        update_method: rebase
  - name: automatic merge for stable backports when CI passes
    conditions:
      - or:
          - and:
              - check-success=tests / all-tests
              - check-success=tests / docker
          - and:
              - check-success=tests / all-tests (pull_request)
              - check-success=tests / docker (pull_request)
      - check-success=SonarCloud Code Analysis
      - base=stable
      - or:
          - "#approved-reviews-by>=1"
          - author=mergify[bot]
    actions:
      queue:
        name: stable
        method: rebase
        rebase_fallback: none
        update_method: rebase
  - name: copy patches to stable branch
    conditions:
      - base=master
      - label!=unstable
    actions:
      backport:
        branches:
          - stable
        assignees:
          - master-of-zen
          - redzic
          - shssoichiro

queue_rules:
  - name: stable
    conditions:
      - or:
          - and:
              - check-success=tests / all-tests
              - check-success=tests / docker
          - and:
              - check-success=tests / all-tests (pull_request)
              - check-success=tests / docker (pull_request)

  - name: default
    conditions:
      - or:
          - and:
              - check-success=tests / all-tests
              - check-success=tests / docker
          - and:
              - check-success=tests / all-tests (pull_request)
              - check-success=tests / docker (pull_request)
