[package]
name = "av1an"
version = "0.4.1"
authors = ["Zen <master_of_zen@protonmail.com>"]
description = """
Cross-platform command-line AV1 / VP9 / HEVC / H264 encoding framework with per scene quality encoding [Command line library]
"""
repository = "https://github.com/master-of-zen/Av1an"
keywords = ["video"]
categories = ["command-line-utilities"]
license = "GPL-3.0"
rust-version = "1.63"
edition = "2021"
readme = "../README.md"

[[bin]]
name = "av1an"
path = "src/main.rs"

[dependencies]
atty = "0.2.14"
clap = { version = "4.0.32", features = ["derive"] }
shlex = "1.0.0"
path_abs = "0.5.1"
anyhow = "1.0.42"
av1an-core = { path = "../av1an-core", version = "0.4.1" }
thiserror = "1.0.30"
once_cell = "1.8.0"
ansi_term = "0.12.1"

[dependencies.flexi_logger]
version = "0.22.0"
default-features = false
features = ["colors", "use_chrono_for_offset"]

[build-dependencies.vergen]
version = "7.0.0"
default-features = false
features = ["git", "build", "rustc", "cargo"]

[dependencies.ffmpeg]
package = "ffmpeg-the-third"
version = "1.2.0"
features = ["serialize"]

[features]
default = []
ffmpeg_static = ["ffmpeg/static", "ffmpeg/build", "av1an-core/ffmpeg_static"]
